name: scala3doc CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:

  build:
    runs-on: [self-hosted, Linux]
    container: lampepfl/dotty:2020-04-24

    # timeout-minutes: 20 We need much more for first run

    steps:
      - name: Set JDK 11 as default
        run: echo "/usr/lib/jvm/java-11-openjdk-amd64/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags

      - name: set right cwd
        run: cd scala3doc

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Compile and test
        run: sbt compile test

      - name: Locally publish self
        run: sbt publishLocal

      - name: Generate test documentation
        run: sbt generateSelfDocumentation

      - name: Generate documentation for dotty library
        run: sbt generateDottyLibDocumentation      

      - name: Generate documentation with SBT plugin
        run: sbt example-project/doc
